### ISSUE TITLE
Android 5.0 error

### ISSUE THREAD

**Issue by crossle** [Kickflip/kickflip-android-sdk#17]
```
      Texture2dProgram  D  Created program 9 (TEXTURE_EXT)
           FFmpegMuxer  I  PrepareAVFormatContext for path /storage/emulated/0/MySampleApp/60c63b9e-1abc-4a7e-9bc5-3923083d2ac1/index.m3u8
        AndroidRuntime  E  FATAL EXCEPTION: CameraEncoder
                        E  Process: io.kickflip.sample, PID: 20050
                        E  java.nio.ReadOnlyBufferException
                        E      at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:354)
                        E      at io.kickflip.sdk.av.FFmpegMuxer.captureH264MetaData(FFmpegMuxer.java:292)
                        E      at io.kickflip.sdk.av.FFmpegMuxer.handleWriteSampleData(FFmpegMuxer.java:206)
                        E      at io.kickflip.sdk.av.FFmpegMuxer.writeSampleData(FFmpegMuxer.java:183)
                        E      at io.kickflip.sdk.av.AndroidEncoder.drainEncoder(AndroidEncoder.java:100)
                        E      at io.kickflip.sdk.av.CameraEncoder.handleFrameAvailable(CameraEncoder.java:433)
                        E      at io.kickflip.sdk.av.CameraEncoder.access$200(CameraEncoder.java:27)
                        E      at io.kickflip.sdk.av.CameraEncoder$EncoderHandler.handleMessage(CameraEncoder.java:835)
                        E      at android.os.Handler.dispatchMessage(Handler.java:102)
                        E      at android.os.Looper.loop(Looper.java:135)
                        E      at io.kickflip.sdk.av.CameraEncoder.run(CameraEncoder.java:610)
                        E      at java.lang.Thread.run(Thread.java:818)
               Process  I  Sending signal. PID: 20050 SIG: 9

```

**Comment by OnlyInAmerica** [comment]
Please see [8600e94](https://github.com/Kickflip/kickflip-android-sdk/commit/8600e9494ad8352472100d165f767f797a96aadc) addresses your issue. I'll update when this fix is included in our next release to Maven Central in the coming days.

**Comment by OnlyInAmerica** [comment]
Closing. Feel free to re-open if you have any trouble.
