### ISSUE TITLE
Crashing when stop playing recorded livestream 

### ISSUE THREAD

**Issue by 4netinteractive** [Kickflip/kickflip-android-sdk#36]
On some Android 4.2 devices we tested we have sometimes the issue that it crashes at the end of the recorded livestream with the Kickflip MediaPlayer integrated in the SDK.

Any idea what causes this and how this can be solved?

Stacktrace:
E/AndroidRuntime﹕ FATAL EXCEPTION: main
Process: com.cloozup.app, PID: 31217
java.lang.IllegalStateException
at android.media.MediaPlayer.getCurrentPosition(Native Method)
at io.kickflip.sdk.fragment.MediaPlayerFragment.getCurrentPosition(MediaPlayerFragment.java:245)
at android.widget.MediaController.setProgress(MediaController.java:423)
at android.widget.MediaController.access$500(MediaController.java:71)
at android.widget.MediaController$3.handleMessage(MediaController.java:394)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:157)
at android.app.ActivityThread.main(ActivityThread.java:5356)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
at dalvik.system.NativeStart.main(Native Method)

**Comment by OnlyInAmerica** [comment]
Kickflip's minimum Android version is 4.3, but if all you're doing is playback that should be fine.

Would you be able to email me the link of the stream in question? It's possible the manifest was corrupted. Feel free to email me (see my Github profile for my address).

Aso I must say that Google's [ExoPlayer](https://github.com/google/ExoPlayer) is now the best choice for HLS playback on Android.

**Comment by 4netinteractive** [comment]
Hi,

Thanks for your quick reply. I don't think a manifest is corrupted because it only happens now and then. The devices were tested with android 4.4.2 (sorry not 4.2). We will have a look at the ExoPlayer and see if that is doing better.
