### ISSUE TITLE
i meet some exception

### ISSUE THREAD

**Issue by woniu0936** [Kickflip/kickflip-android-sdk#59]
java.lang.IllegalStateException
                                                                     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                                                     at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1036)
                                                                     at com.gouhuoapp.camerarecord.video.AndroidEncoder$override.drainEncoder(AndroidEncoder.java:86)
                                                                     at com.gouhuoapp.camerarecord.video.AndroidEncoder$override.access$dispatch(AndroidEncoder.java)
                                                                     at com.gouhuoapp.camerarecord.video.AndroidEncoder.drainEncoder(AndroidEncoder.java:0)
                                                                     at com.gouhuoapp.camerarecord.video.CameraEncoder.handleFrameAvailable(CameraEncoder.java:497)
                                                                     at com.gouhuoapp.camerarecord.video.CameraEncoder.access$100(CameraEncoder.java:28)
                                                                     at com.gouhuoapp.camerarecord.video.CameraEncoder$EncoderHandler.handleMessage(CameraEncoder.java:913)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at com.gouhuoapp.camerarecord.video.CameraEncoder.run(CameraEncoder.java:676)
                                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by woniu0936** [comment]
in MediaCodec，i find below：
/**
     \* Dequeue an output buffer, block at most "timeoutUs" microseconds.
     \* Returns the index of an output buffer that has been successfully
     \* decoded or one of the INFO_\* constants.
     \* @param info Will be filled with buffer meta data.
     \* @param timeoutUs The timeout in microseconds, a negative timeout indicates "infinite".
     \* @throws IllegalStateException if not in the Executing state,
     \*         or codec is configured in asynchronous mode.
     \* @throws MediaCodec.CodecException upon codec error.
     _/
    @OutputBufferInfo
    public final int dequeueOutputBuffer(
            @NonNull BufferInfo info, long timeoutUs) {
        int res = native_dequeueOutputBuffer(info, timeoutUs);
        synchronized(mBufferLock) {
            if (res == INFO_OUTPUT_BUFFERS_CHANGED) {
                cacheBuffers(false /_ input */);
            } else if (res >= 0) {
                validateOutputByteBuffer(mCachedOutputBuffers, res, info);
                if (mHasSurface) {
                    mDequeuedOutputInfos.put(res, info.dup());
                }
            }
        }
        return res;
    }

**Comment by woniu0936** [comment]
IllegalStateException if  codec is configured in asynchronous mode？？in VideoEncoderCore you say “This class is not thread-safe, with one exception: it is valid to use the input surface  on one thread, and drain the output on a different thread.”

**Comment by woniu0936** [comment]
It's really nice if you can help check it.
